version: '3.8'
volumes:
  mongodb-data:
  cache-data:
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data/cache
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    environment:
      # Set the Redis Commander options
      REDIS_HOSTS: "redis"  # Points to the 'redis' service defined above
    depends_on:
      - redis
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
networks:
  default:
    external: true
    name: local